[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[redirects]]
  from = "/"
  to = "https://cowbunnyst.farm/"
  status = 200
  force = true
  [redirects.headers]
    Connection = "Upgrade"
    Upgrade = "websocket"
